---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  name: app1-sa
  namespace: app1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app1
  name: app1-full-access-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-sa-role-binding
  namespace: app1
subjects:
  - kind: ServiceAccount
    name: app1-sa
    namespace: app1
roleRef:
  kind: Role
  name: app1-full-access-role
  apiGroup: rbac.authorization.k8s.io
