---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  name: app1-sa
  namespace: app1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  namespace: app1
  name: app1-full-access-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  name: app1-sa-role-binding
  namespace: app1
subjects:
  - kind: ServiceAccount
    name: app1-sa
    namespace: app1
roleRef:
  kind: Role
  name: app1-full-access-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  name: gotk-reconciler
  namespace: app1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:apps:reconciler
  - kind: ServiceAccount
    name: app1-sa
    namespace: app1