apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app1-application
  namespace: app1
spec:
  serviceAccountName: app1-sa
  interval: 1m
  path: ./deployment/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: app1
  validation: client
