---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app2
  name: app2-sa
  namespace: app2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app2
  name: app2-full-access-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app2-sa-role-binding
  namespace: app2
subjects:
  - kind: ServiceAccount
    name: app2-sa
    namespace: app2
roleRef:
  kind: Role
  name: app2-full-access-role
  apiGroup: rbac.authorization.k8s.io
