apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app2-application
  namespace: app2
spec:
  interval: 5m0s
  path: ./deployment/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: app2
  validation: client
