---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: platform
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: ">=4.0.0 <5.0.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: platform
      interval: 1m
